# @package _global_

rewards:
  _target_: "envs.rewards.motion_tracking.MotionTrackingRewards"

  split_sides: ${per_hand_actor_critic}

  reward_weights:
    # ── Task ─────────────────────────────────
    tracking_obj_pcd_match_error_exp: 1.0
    tracking_ref_mano_tip_distance_bound_exp: 0.3

    # ── Motion Tracking ──────────────────────
    #   Wrist
    tracking_ref_mano_wrist_trans_error_exp: 0.15
    tracking_ref_mano_wrist_rot_error_exp:   0.15
    #   Fingers
    #     Translation
    tracking_ref_mano_tip_trans_error_exp: 0.3
    #     Joint Pos
    tracking_joint_pos_bc_exp: 0.3

    # ── Regularization ────────────────────────
    action_penalty: -0.01
    termination_penalty: -100.0

  reward_scales:
    # ── Task ─────────────────────────────────
    tracking_obj_pcd_match_error_exp: 10.0

    # ── Motion Tracking ──────────────────────
    #   Wrist
    tracking_ref_mano_wrist_trans_error_exp: 10.0
    tracking_ref_mano_wrist_rot_error_exp:    3.0
    #   Fingers
    #     Translation
    tracking_ref_mano_tip_trans_error_exp: 20.0
    #     Joint Pos
    tracking_joint_pos_bc_exp: 500.0

  reward_params:
    tracking_obj_pcd_match_error_exp: { n_points: 128, topk: 3, norm_radius: 0.058 }
